### ISSUE TITLE
The link "http://j.mp/ui-harness" provided in the quick start returns "Not Found"

### ISSUE THREAD

**Issue by chrishannaby** [philcockfield/ui-harness#1]
Looks like a folder reorganisation has broken the link. Script is now located here
https://raw.githubusercontent.com/philcockfield/ui-harness/master/sh/create.sh

**Comment by philcockfield** [comment]
Cool - thanks @chrishannaby.  Have updated it to the proper URL now - which is also on the http://www.uiharness.com/ site.
