### ISSUE TITLE
Make UI Harness API more functional

### ISSUE THREAD

**Issue by frederickfogerty** [philcockfield/ui-harness#24]
Right now the UIHarness API uses `this` as it’s primary interaction - from purely a style choice I would envisage that passing the component as the first prop to the `describe` wrapper would make it more functional.

Also what happens if arrow functions are not used in the bdd functions? Does it still work correctly? Maybe the functions get bound to another context?

Also I would suggest changing the names to something like `mergeProps`. Maybe then methods like `getProps` or `clearProps` could be introduced.

Low priority but just something to think about

**Comment by philcockfield** [comment]
Cool - regarding the first part of this issue, I created this issue a few minutes ago: https://github.com/philcockfield/ui-harness/issues/23

**Comment by philcockfield** [comment]
Closing this issue to focus conversation within #42
