### ISSUE TITLE
Add functionality to pass spies to component

### ISSUE THREAD

**Issue by frederickfogerty** [philcockfield/ui-harness#25]
Right now UIHarness tests how a component looks, but not how it works. With this, we can check that it calls the right handlers at the right times. 

In terms of UI, I envisage a separate section in the sidebar with a title like “Registered Spies” and then the prop name. When it’s triggered, it could flash and then fade, and potentially give an option to see what parameters it was called with.

Example
```js
<TextInput
  onChange={ () => {} } // I want to see when this is called
/>
```

**Comment by philcockfield** [comment]
A callback like that works now in the `Suite` (`describe` block).  I typically just write it to the console - so the idea here is surfacing this as helpful UI, right?  Or is there something else to this you're thinking of @frederickfogerty?

I like. :+1:

**Comment by frederickfogerty** [comment]
Yep that's exactly what I was thinking @philcockfield

**Comment by philcockfield** [comment]
Cool.  Gonna start thinking about some kind of generically powerful panel to surface this kind of stuff on.

**Comment by philcockfield** [comment]
The sequence of calls (along with the params) becomes important, or helpful, to visualize.

**Comment by frederickfogerty** [comment]
@philcockfield that's definitely true, I hadn't thought about that

**Comment by philcockfield** [comment]
@frederickfogerty - going to close this until we feel a concrete need in day-to-day usage.
