### ISSUE TITLE
sh install not working on "npm start"

### ISSUE THREAD

**Issue by jachinte** [philcockfield/ui-harness#3]
Hello,

I run the web-sh install to try ui-harness but the following error is raised. I'm using the latest stable version of node on mac.

```
+|-------------------------------------------------------
   Module created and initialized successfully.
   Automaticaly starting the server now using:

      npm start

   Open your browser at http://localhost:3030
-|-------------------------------------------------------

> ui2@1.0.0 start /Users/migueljimenez/Desktop/ui2
> node ./node_modules/ui-harness/server --entry ./src/specs

module.js:340
    throw err;
    ^

Error: Cannot find module 'babel/register'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.start (/Users/migueljimenez/Desktop/ui2/node_modules/ui-harness/lib/server/middleware.js:254:5)
    at Object.<anonymous> (/Users/migueljimenez/Desktop/ui2/node_modules/ui-harness/server.js:35:16)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! ui2@1.0.0 start: `node ./node_modules/ui-harness/server --entry ./src/specs`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ui2@1.0.0 start script 'node ./node_modules/ui-harness/server --entry ./src/specs'.
npm ERR! This is most likely a problem with the ui2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./node_modules/ui-harness/server --entry ./src/specs
npm ERR! You can get their info via:
npm ERR!     npm owner ls ui2
npm ERR! There is likely additional logging output above.
```

**Comment by philcockfield** [comment]
Ah, I see what's happening. Away from a keyboard but will fix shortly.
Thanks!

**Comment by jachinte** [comment]
Sweet, I'll keep an eye out for future updates on this

**Comment by philcockfield** [comment]
Hey there @jachinte 

I've change tack away from the `sh` script, and am now pointing at a sample git repo.  Functionally equivalent, but I think a little less "non-standard".

Details on the updated landing page at: http://uiharness.com/

![screen shot 2016-01-13 at 2 03 55 pm](https://cloud.githubusercontent.com/assets/185555/12281860/803904d4-b9fe-11e5-93ef-58830a9953f7.png)

**Comment by jachinte** [comment]
Hi @philcockfield, I understand why the change, it seems more transparent now. However, the error remains when executing the "npm start" command. Do you think this is related to ui-harness or to one of its dependencies?

**Comment by jachinte** [comment]
It seems the error is being caused by a typo in [middleware.js#L189](https://github.com/philcockfield/ui-harness/blob/master/src/server/middleware.js#L189): it should be `babel-register`, instead of `babel/register`. However, after correcting the error and starting the server, a reference error is thrown: ReferenceError: [BABEL] /Users/.../ui-harness-sample/src/specs/index.js: Unknown option: base.stage

**Comment by philcockfield** [comment]
@jachinte oh, sorry.  Good catch!

I've updated that call to use the babel-6 version.  Weird that didn't show up on my system when testing.
Is it working for you now?

**Comment by jachinte** [comment]
@philcockfield after pulling the changes and running gulp, the error remains. Here is the complete stack trace:
```
iMac-de-Miguel:ui-harness migueljimenez$ node server --entry /Users/migueljimenez/Desktop/ui-harness-sample/src/specs

Starting (development)...
/Users/migueljimenez/Desktop/ui-harness/node_modules/babel-core/lib/transformation/file/logger.js:41
    throw new Constructor(this._buildMessage(msg));
    ^

ReferenceError: [BABEL] /Users/migueljimenez/Desktop/ui-harness-sample/src/specs/index.js: Unknown option: base.stage
    at Logger.error (/Users/migueljimenez/Desktop/ui-harness/node_modules/babel-core/lib/transformation/file/logger.js:41:11)
    at OptionManager.mergeOptions (/Users/migueljimenez/Desktop/ui-harness/node_modules/babel-core/lib/transformation/file/options/option-manager.js:262:18)
    at OptionManager.init (/Users/migueljimenez/Desktop/ui-harness/node_modules/babel-core/lib/transformation/file/options/option-manager.js:416:10)
    at File.initOptions (/Users/migueljimenez/Desktop/ui-harness/node_modules/babel-core/lib/transformation/file/index.js:191:75)
    at new File (/Users/migueljimenez/Desktop/ui-harness/node_modules/babel-core/lib/transformation/file/index.js:122:22)
    at Pipeline.transform (/Users/migueljimenez/Desktop/ui-harness/node_modules/babel-core/lib/transformation/pipeline.js:42:16)
    at Object.transformFileSync (/Users/migueljimenez/Desktop/ui-harness/node_modules/babel-core/lib/api/node.js:116:10)
    at compile (/Users/migueljimenez/Desktop/ui-harness/node_modules/babel-register/lib/node.js:102:20)
    at loader (/Users/migueljimenez/Desktop/ui-harness/node_modules/babel-register/lib/node.js:130:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/migueljimenez/Desktop/ui-harness/node_modules/babel-register/lib/node.js:140:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at /Users/migueljimenez/Desktop/ui-harness/lib/server/middleware.js:76:12
    at Array.forEach (native)
``

**Comment by philcockfield** [comment]
Hmmmm

**Comment by jachinte** [comment]
Does it work when you clone the dummy example? It may be something with my machine, I can try it in an isolated environment (a virtual machine, for example).

**Comment by philcockfield** [comment]
Yeah, I've tested it from a cold start (fresh folder).  I'm getting friend ( @nicwise ) to test it out on his machine to see if it's environmental.

Do you have babel installed globally @jachinte.  And if so, what version?

**Comment by jachinte** [comment]
@philcockfield No, I didn't. I installed latest version (6.4.0) and it continues throwing the same reference error.

**Comment by philcockfield** [comment]
@jachinte - thanks.

**Comment by philcockfield** [comment]
@jachinte, when you say:

>>  I'm using the latest stable version of node on mac.

Is that `5.x.x`?  If you're on `4.x.x` I think I can see what the problem is.  Thanks

**Comment by jachinte** [comment]
@philcockfield I'm very sorry. When I executed `git pull` I didn't notice that changes in middleware.js were not applied because of some changes I manually performed. After re-doing everything again it worked, however some dependencies were not found and I had to manually install them: `babel-plugin-transform-class-properties`, `babel-preset-es2015`, `babel-preset-stage-0`, `babel-preset-react`, and `react`. I know these are specified in the `.babelrc` file but unfortunatelly I am not familiar with it so I couldn't make it work. Maybe some link or litle explanation in the dummy repository can help :+1: 
Thank you very much for your help. Is there some documentation available to get started using ui-harness?

FYI: I'm using node v4.2.4

**Comment by philcockfield** [comment]
Ah!  That's the issue - node `4.x`.  

It seems they changed thing quite radically with node `5.x` whereby the copy all of the dependencies into the root `node_modules` as peer dependencies.

This is what UIHarness is relying on (and hence why it's getting "not found" errors), and ultimately allows for a very slim package.json dependency declaration:

      "devDependencies": {
        "ui-harness": "^2.0.0"
      }


I put a node engine statement in the package.json to try and force `>=5`, but that doesn't seem to do a whole hell of a lot.

    "engines": { "node": ">=5.0.0" }

**Comment by philcockfield** [comment]
I've tried to make that a little more explicit on the site landing-page:

![image](https://cloud.githubusercontent.com/assets/185555/12306441/a388840a-ba9e-11e5-854f-b2777dac0f6c.png)

**Comment by jachinte** [comment]
I upgraded node to v5.4.1 and it's working like a charm. Thanks!

**Comment by philcockfield** [comment]
Beaut!! @jachinte 
:smile:
