### ISSUE TITLE
API Options

### ISSUE THREAD

**Issue by frederickfogerty** [philcockfield/ui-harness#42]
Continuing on from various discussions in #31, #24, #23 and #38, this are my latest ideas for an API
### "Current"

``` js
describe('MyComponent', function () {
  this.component(<MyComponent counter={1} />)
  it('label', () => this.props({ counter: 2 }))
})
```
### Declarative v1

``` js
describe('MyComponent', function () {
  this.component(<MyComponent counter={1} />)
  it('label', ({ props: { counter: 2 } })) // can be a function or just an object
})
```
### Declarative v2

``` js
describe('MyComponent', function () {
  it('label', <MyComponent counter={1} />) // can be a function or just an element
  it('other label', <MyComponent counter={2} />) // can be a function or just an element
})
```
### Declarative v3

A mix between v1 and v2

``` js
describe('MyComponent', function () {
  it('label', ({ component: <MyComponent counter={1} />, context: {}, contextTypes: {}, width })) // can be a function or just an element
})
```
### Imperative

``` js
import { component, contextTypes } from 'ui-harness'

describe('MyComponent', function () {
  it('label', () => {
    component(<MyComponent counter={1} />)
    contextTypes({})
  })
})
```
### Imperative v2

``` js
describe('MyComponent', function () {
  it('label', _comp => {
    _comp.component(<MyComponent counter={1} />)
    _comp.contextTypes({}) // can also be chained
  })
})
```
### Functional/Imperative v1

``` js
import { component, contextTypes, width, props } from 'ui-harness'

describe('MyComponent', function () {
  it('label', _comp => {
    component(<MyComponent counter={1} />, this) // this === _comp
    contextTypes({}, _comp) // can also be chained
    // with this we can do stuff like 
    props({ someChildProp: 2 }, _comp.child)
  })
})
```
### Not even sure what to call this

``` js
import { render: _render } from 'react-dom'
import { withContext, ContextWrapper } from 'ui-harness'

const render = curry(_render) // we could provide this
describe('MyComponent', stage => {
  // Stage is a DOM element so we can just use React to render our components
  render(<MyComponent counter={1} />, stage)

  // If they want to do things like context
  render(withContext(<MyComponent counter={1} />, { a: PropTypes.object }, { a: 2 }), stage)

  // or more JSX-y
  render(<ContextWrapper contextTypes={{ a: PropTypes.object }} context={{ a: 2}}><MyComponent counter={1} /></ContextWrapper>, stage)
  it('label', render(<MyComponent counter={1} />)) // Since render is curried, and since the stage is passed in as the first prop, this just re-renders to the current stage
})
```

I think we need to explore this one more

**Comment by philcockfield** [comment]
As per our discussion on the phone - I'm liking the last one for the reasons discussed.

Can you unpack more what `stage` is?  How would the environment of the UIHarness (`width`, `align` etc) be set?  Is that a function on `stage`?

**Comment by frederickfogerty** [comment]
`stage` is simply a DOM element, which you are able to do what you wish with. This way, it removes all the rendering logic out of the core, and the tests simply render straight to "bare metal" if you will. Also, this removes the React coupling - we can test ember components, angular components, basically anything can render into a DOM element.

In the case of React Native, we could replace stage with a `nativeTree` or something similar, but we'd probably have to do something custom as there is no `render` for React native - only a Registry.

**Comment by philcockfield** [comment]
Oh, so the metaphor of `stage` is:

![image](https://cloud.githubusercontent.com/assets/185555/13066062/7ef58898-d4c7-11e5-86c8-fb473dedd72d.png)

Not a "step in a sequence".

**Comment by philcockfield** [comment]
I love how this de-couples from explicitly React.  But even more so is the ReactNative potential.

**Comment by frederickfogerty** [comment]
That's the idea - we're giving you a stage to show off your component and to test your component. We provide all the crew in the wings, letting you focus on what really matters.

**Comment by philcockfield** [comment]
I like that.  "Stage" has the ambiguity of "process," however "canvas" is a totally loaded term that you can guarantee people will misinterpret.

**Comment by philcockfield** [comment]
How do we change props?  Something like this?

    describe('MyComponent', stage => {
      render(<MyComponent counter={1} />, stage)

      it('color:red', props({ color: 'red' }));

    })


Also, would changing the environment (width, background, header etc) be functions called on the `stage`?

**Comment by frederickfogerty** [comment]
### Prop updates (Idea One):
```js
const replaceProps = curry((Component, props, stage) => render(<Component {...props} />, stage))

describe('MyComponent', stage => {
  render(<MyComponent counter={1} />, stage) // explicit set

  it('color:red', render(<MyComponent counter={2} />)) // replace props

  const renderWithProps = replaceProps(MyComponent) // partially applied
  it('color:red', renderWithProps({ counter: 2 })) // since it was partially applied before, it already
                                                                          // knows which component to render, thus less state
})
```

### Prop updates (Idea Two):
Change function signature of it/describe from `stage -> void` to `stage, component -> void`  
```js
const replaceProps = curry((props, stage, Component) => render(<Component.type {...props} />), stage)
// now we can do this
const mergeProps = curry((props, stage, Component) => render(<Component.type {...Component.props} {...props} />), stage)
// or 
import u from 'updeep'
const mergeProps = curry((props, stage, Component) => {
  const newProps = u(props, Component.props)
  render(<Component.type {...newProps} />), stage)
}

describe('MyComponent', stage => {
  render(<MyComponent counter={1} />, stage) // explicit set

  it('color:red', render(<MyComponent counter={2} />)) // replace props

  // const renderWithProps = replaceProps(MyComponent)  // not needed anymore
  it('color:red', replaceProps({ counter: 2 }))

  // now we can merge props too
  it('color:red', mergeProps({ text: 'Hey this API is going to pay off big time' }))
})
```

**Comment by philcockfield** [comment]
Thanks @frederickfogerty - I'm cogitating :thought_balloon:  on these :wink: ....

**Comment by philcockfield** [comment]
It looks like there's a mix of "implementation" and "usage" in here - is that so.

Namely the `udeep` and `mergeProps` | `replaceProps`.  Are you thinking this would be boilerplate a user would copy into the `.spec.js` file?  Or would we, optionally, wrap that in something like a `uih` module that gets imported with those functions exposed @frederickfogerty ?

**Comment by frederickfogerty** [comment]
That's exactly it - I was merely showing that these methods don't have to be baked into the core, much like in Redux you have the connector, selectors, reselect, etc. which are all in "user-land", rather than baked into the core of redux.

I was thinking we would provide these as named exports on the `ui-harness` module, but the user is free to choose their own implementation.

**Comment by philcockfield** [comment]
Cool cool!

**Comment by philcockfield** [comment]
What's beautiful is how easy and clear it is to extend the behavior yourself without having to change the UIHarness.  Just wrap the right function, and do your own thing - or pick the "common" one from the default exports.

**Comment by frederickfogerty** [comment]
I think we'll definitely have to try it out before we publish it to make sure it will work

**Comment by frederickfogerty** [comment]
### Prop updates (Idea 3)

Introduce another user-land helper, `withManagedState`
The uih core function signature is still `stage -> void`, but we provide a HOF which changes the signature to idea two's: `(stage, component) -> void`

```js
// Same as idea 2
import u from 'updeep'
const mergeProps = curry((props, stage, Component) => {
  const newProps = u(props, Component.props)
  render(<Component.type {...newProps} />), stage)
}

// Implementation
import { render } from 'react-dom'
let withManagedState
(() => { // wrap in an IIFE to hide state (just use a CJS module)
  let component // somewhere to store the current component
  const _render = (_component, stage) => {
    component = _component
    render(_component, stage)
  }
  const it, context // some implementation for it and context to pass down component
  managedState = handler => stage => {
    handler({ stage, component, render: _render, it, context }) 
  }
})()

// User-land spec file
describe('MyComponent', stage => {
  render(<MyComponent counter={1} />, stage) // explicit set

  it('color:red', render(<MyComponent counter={2} />)) // replace props

  // now we can merge props too
  it('color:red', mergeProps({ text: 'Hey this API is going to pay off big time' }))
})
```

### Prop updates (Idea 4)

Overload `render` to accept a type or a function, beauty is that it doesn't change it function signature (still `stage -> void`)

```js
import u from 'updeep'
const mergeProps = curry((props, stage) => 
  render(state => <Component.type {...u(props, state.props)} />), stage)
)

// Implementation
import { render: _render } from 'react-dom'
const render = (funcOrComponent, stage) => {
  if (isFunc(funcOrComponent)) {
    return _render(funcOrComponent(currentState), stage) // currentState is our internally managed (or user-land managed, like idea 3) component state
  }
  return _render(funcOrComponent, stage)
}

// User-land
describe('MyComponent', stage => {
  render(<MyComponent counter={1} />, stage) // explicit set

  it('color:red', render(<MyComponent counter={2} />)) // replace props

  // now we can merge props too
  it('color:red', mergeProps({ text: 'Hey this API is going to pay off big time' }))
})
```

**Comment by philcockfield** [comment]
>> I think we'll definitely have to try it out before we publish it to make sure it will work

@frederickfogerty - totally, this is what's great about UIHarness - it's a real "eat your own dog-food" kinda project.
