### ISSUE TITLE
Support to colocate specs with files

### ISSUE THREAD

**Issue by frederickfogerty** [philcockfield/ui-harness#48]
Right now I colocate my tests with my files using `.test.js`. Would be cool if we could do this with ui-harness. If this is already possible, let me know and I'll close this.

**Comment by philcockfield** [comment]
All specs are included via module references (no magic folder scanning or anything going on) - so this is possible.

What could be done is adding a folder scan for `.spec.js` files, but that's additional "magic" that may or may not be a good thing.  Let's discuss.

**Comment by frederickfogerty** [comment]
@philcockfield you could add a file option at the command line where the consumer could use a glob to select files, something like `uih app/**/*.uih.js`
