### ISSUE TITLE
Add mention-bot

### ISSUE THREAD

**Issue by frederickfogerty** [philcockfield/ui-harness#49]
You know, for that sweet PR workflow.

### How To Use?

- Go to
 - your project on GitHub > Settings > Webhooks & services > Add Webhook or
 - your organization on GitHub > Settings > Webhooks > Add Webhook
- Payload URL: `https://mention-bot.herokuapp.com/`
- Let me select individual events > Check `Pull Request`
- Add Webhook

And you are done. Next time a pull request is opened, you should see the bot add a comment ;)

https://github.com/facebook/mention-bot

**Comment by philcockfield** [comment]
![image](https://cloud.githubusercontent.com/assets/185555/13333462/0654d1bc-dc6c-11e5-82e3-e61765458e08.png)

Webhook added. Anything else to do @frederickfogerty

**Comment by frederickfogerty** [comment]
@philcockfield Nope... not sure if it's working though. Tried on my other repo https://github.com/imgix/react-imgix and it doesn't seem to have worked.

**Comment by frederickfogerty** [comment]
Closing as it is working, evident in #52.
