### ISSUE TITLE
Css loaders

### ISSUE THREAD

**Issue by fabiokandrade** [philcockfield/ui-harness#51]
It would be great, if we could use a css loader or css modules.
Is this planned?
tks!!

**Comment by philcockfield** [comment]
@fabiokandrade would you see that as passing an option in to the web-pack builder?

**Comment by fabiokandrade** [comment]
yes, it could be an option through .uiharness.yml

**Comment by philcockfield** [comment]
That sounds like the right place for it. 
Could you drop an example of the webpack config for your CSS loader and modules here, please?

**Comment by nimerritt** [comment]
+1 for this!

**Comment by fabiokandrade** [comment]
I have to admit that I am not a webpack expert and configuring it is kind of tricky for me. I'm following this css-modules example [ https://github.com/css-modules/webpack-demo/blob/master/webpack.config.js]( https://github.com/css-modules/webpack-demo/blob/master/webpack.config.js)

**Comment by frederickfogerty** [comment]
Yeah, if you're using `css-loader` all you have to do is add `?modules` and you're away. We could expose this as a simple flag in .uiharness.yml as it will be common use case, and then maybe have a method in the node API like `overrideLoaders: Array → Array` where it is passed the current loaders array and can override, append, modify, etc.

**Comment by fabiokandrade** [comment]
I think this approach of a simple way to turn on the css-loader with a basic configuration would be great!

Overriding loaders might be more difficult to implement and could be left to a second stage, don't you think? It would be necessary to deal not only with the loaders array but also eventually with each plugin instantiation (plugins array).

**Comment by philcockfield** [comment]
Yeah - I'm getting the main CSS loader plugin in there now.  Want to make the web-pack configuration completely extensible at some point, but as you point out, don't want to rush it out for just this and have it be idiosyncratic to CSS loading.  Rather I'd like to have it powerfully general purpose.

**Comment by frederickfogerty** [comment]
@fabiokandrade definitely could be left to a later stage, I'm just putting some ideas out there. I don't think plugin instantiation would be that much of an issue - usually in webpack you don't need to instantiate plugins, webpack handles that for you.

**Comment by nickradford** [comment]
+1 to this, an option in the `.uiharness.yml` would be helpful

**Comment by dbuarque** [comment]
+1

**Comment by kalmanb** [comment]
+1
