### ISSUE TITLE
Support new `Stateless function components`

### ISSUE THREAD

**Issue by philcockfield** [philcockfield/ui-harness#53]
As of React 0.14.
https://facebook.github.io/react/blog/2015/09/10/react-v0.14-rc1.html#stateless-function-components

![image](https://cloud.githubusercontent.com/assets/185555/13551356/e2b29956-e39b-11e5-8de8-a4966ba44e81.png)

**Comment by frederickfogerty** [comment]
What needs to change to get this to work? Does `this.component(Aquarium)` not work?

**Comment by philcockfield** [comment]
@frederickfogerty there's something funny going on - I'm writing up some tests now.

**Comment by philcockfield** [comment]
Works find (when capitalized as pointed out by @frederickfogerty).  Test now exists to prove this.
