### ISSUE TITLE
Get working with Meteor + React?

### ISSUE THREAD

**Issue by jackjwilliams** [philcockfield/ui-harness#58]
I love the idea behind this and wanted to get this working with Meteor + React, starting from the simple-todos-react tutorial from Meteor. But I'm having a difficult time. Basically I did the following:

meteor create simple-todos-react
... follow tutorial ...
meteor add react
... create Task.jsx ...

Add custom folders specs, with index.js:

```
describe("Todos React", function(){
    require("./Task.spec");
});
```

Create Task.spec.jsx (shell - coming from uiharness starter)

```
import React from "react";
import Task from "../Task";

const LOREM = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.";

describe('Task', function(){
    this.header(`## Task`);
    
    before(() => {
    // Runs when the Suite loads.
    // Use this to load your component-under-test.
        this.component(<Task />);
    });
    
    
    it('reload', () => {
        this.component(<Task/>); 
    });
});
```

npm init in base folder, package.json as follows:

```
{
  "name": "simple-todos-react",
  "version": "1.0.0",
  "description": "None",
  "main": "index.js",
  "dependencies": {},
  "devDependencies": {
    "ui-harness": "^3.7.1",
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node ./node_modules/ui-harness/start --entry=./specs"
  },
  "author": "",
  "license": "ISC"
}
```

But I continue to get the following error when running npm start:

```
Unhandled rejection SyntaxError: C:/Projects/meteor/simple-todos-react/specs/Task.spec.jsx: Unexpected token (12:23)
  10 |     // Runs when the Suite loads.
  11 |     // Use this to load your component-under-test.
> 12 |         this.component(<Task />);
     |                        ^
  13 |     });
  14 |
  15 |
    at Parser.pp.raise (C:\Projects\meteor\simple-todos-react\node_modules\babylon\index.js:1378:13)
    at Parser.pp.unexpected (C:\Projects\meteor\simple-todos-react\node_modules\babylon\index.js:2817:8)
    at Parser.pp.parseExprAtom (C:\Projects\meteor\simple-todos-react\node_modules\babylon\index.js:749:12)
    at Parser.pp.parseExprSubscripts (C:\Projects\meteor\simple-todos-react\node_modules\babylon\index.js:504:19)
    at Parser.pp.parseMaybeUnary (C:\Projects\meteor\simple-todos-react\node_modules\babylon\index.js:484:19)
    at Parser.pp.parseExprOps (C:\Projects\meteor\simple-todos-react\node_modules\babylon\index.js:415:19)
    at Parser.pp.parseMaybeConditional (C:\Projects\meteor\simple-todos-react\node_modules\babylon\index.js:397:19)
    at Parser.pp.parseMaybeAssign (C:\Projects\meteor\simple-todos-react\node_modules\babylon\index.js:360:19)
    at Parser.pp.parseExprListItem (C:\Projects\meteor\simple-todos-react\node_modules\babylon\index.js:1206:16)
    at Parser.pp.parseCallExpressionArguments (C:\Projects\meteor\simple-todos-react\node_modules\babylon\index.js:580:20)
    at Parser.pp.parseSubscripts (C:\Projects\meteor\simple-todos-react\node_modules\babylon\index.js:543:29)
    at Parser.pp.parseExprSubscripts (C:\Projects\meteor\simple-todos-react\node_modules\babylon\index.js:514:15)
    at Parser.pp.parseMaybeUnary (C:\Projects\meteor\simple-todos-react\node_modules\babylon\index.js:484:19)
    at Parser.pp.parseExprOps (C:\Projects\meteor\simple-todos-react\node_modules\babylon\index.js:415:19)
    at Parser.pp.parseMaybeConditional (C:\Projects\meteor\simple-todos-react\node_modules\babylon\index.js:397:19)
    at Parser.pp.parseMaybeAssign (C:\Projects\meteor\simple-todos-react\node_modules\babylon\index.js:360:19)
```

**Comment by frederickfogerty** [comment]
Hey @jackjwilliams. Great to have you trying to use the ui-harness. Some reasons I think that may be affecting you:

- not have `babel-preset-react` installed, which the UI harness actually doesn't import (submitted PR #59). You can run `npm i babel-preset-es2015 babel-preset-react babel-preset-stage-0 babel-plugin-transform-class-properties` as a hot-fix

**Comment by philcockfield** [comment]
Those references were being pulled in by `js-babel` which has not been removed along with explicitly adding the babel references in @frederickfogerty 's #59 PR.  This PR is merged and a new version (`3.7.2`) has been published.

@jackjwilliams is this working for you with Meteor now?

If not, it might be that Meteor is using an older version of Node under the covers - so we may see other issues arise as (at the moment) UIHarness has a pretty high minimum node version requirement (5+). #26 aims at reducing the minimum node version.

**Comment by jackjwilliams** [comment]
@philcockfield Yes it did, thanks! The next issue I ran into is that my react components had to be defined as

`export default class Task extends React.Component`

rather than

`Task = React.createClass`

I'm still new to this whole world - but that worked for me!

Thanks

**Comment by philcockfield** [comment]
Interesting @jackjwilliams - not sure what `React.createClass` wouldn't work.  But great that it's working - and anyways - defining your component using the `class` is the better way to do it these days :smile: 

I'll close this issue now.  Cheers!

**Comment by philcockfield** [comment]
Hey @jackjwilliams - I'm curious - how are you using the UIHarness in it's current state with Meteor? I'd be curious to see a sample of what you're doing if you'd be cool with sharing.

Was chatting with someone up in Meteor yesterday, and got to thinking about this issue, then realized: "hang on, what was Jack doing? Meteor serves and bundles it's own stuff, while the UIHarness is using webpack and the dev-server to bundle and serve."

**Comment by jackjwilliams** [comment]
Well I'll remind you I'm new to React and Meteor! So this might not even be doable (although, I did get it working finally). I might be completely misunderstanding the use-case and or the way to use UI Harness correctly.

So when I found Meteor I was intrigued and amazed - I loved it. Then I saw that it worked with React - cool, I'll learn react as well.

Then, at about approx. 2am, eyes bloodshot I found UI Harness and thought what a cool way to do UI design / testing (I found it from reading the meteor documentation). For some reason I got the idea UI Harness was created FOR Meteor. I later learned it's made for React. So I thought, well, Meteor works with React, why couldn't I still use UI Harness (because it's made for React)?

I can push a demo project, but from what you are telling me what I've done might not even be suitable. IE on one side uiharness is using webpack and dev-server and the other is meteor. Two completely different systems - so what it presented in uiharness might not be 100% the same in Meteor.

**Comment by philcockfield** [comment]
Ah, cool @jackjwilliams  - I see where you're coming from.

I'd say that if you're creating clean, isolated components to use within your Meteor app then the UIHarness will be what you want - it just won't be working within the context of Meteor...which is a good thing.  The React way is to have beautifully isolated components that just take props, and as little state as possible.  That's what the UIHarness was designed for - to make creating those, and testing them, easy.

You can create those within an NPM module - with the UIHarness.  From there you can import that module into your Meteor app and use the components the way Meteor tells you to use React.  That would be where you'd start getting your business logic (associated with Meteor's live queries etc) involved.
