### ISSUE TITLE
Suggest best practice to have unit tests and ui specs in one file

### ISSUE THREAD

**Issue by D1no** [philcockfield/ui-harness#60]
As mentioned here #52

It would be annoying if each component would have three files or even four files

- mocha unit test
- ui-harness spec
- (feature file)
- (step file)

New best practice seems to be already to name uni tests `.spec.js` and for the case of meteor, it is picking those files up automatically during test mode.

Would be great if there would be some proposed way to have ui harness spec files also in those unit spec files. Maybe by having ui-harness set an environment global (I did not check if its there already) so that it can just run in a if closure and return.

```js

// Unit and UI Tests

if(UIHARNESS) {
     // ...
     // do ui set-up and run down
     // ...

     // do top level return to skip the mocha stuff
     return true;
}

// mocha unit tests follow

```

When the specs are run by the test runner it will ignore the UI stuff and vice verse due to the pre-top level return.

Note: Top level returns work without a problem in nodeJS. But it is technically not ES6 compliant anymore so babel might complain if you don't run in loose mode (did not check your config).
https://phabricator.babeljs.io/T1298#48727

**Comment by philcockfield** [comment]
Hey there @D1no - this sounds reasonable.

**Comment by philcockfield** [comment]
If it's just adding a global variable flag - that's easy.  Will get that done pronto.  That could be generically useful for other, as of yet un-thought-of scenarios.

**Comment by frederickfogerty** [comment]
`UIHARNESS` -> `__UI_HARNESS__` - in line with common webpack vars like `__DEV__`, `__PRODUCTION__`, etc.

**Comment by philcockfield** [comment]
`__UIHARNESS__`

**Comment by D1no** [comment]
`__UIHARNESS__` 👍🏻

**Comment by philcockfield** [comment]
@D1no this has been pushed in release `3.7.7`.  Details in README.

![image](https://cloud.githubusercontent.com/assets/185555/13912065/cc9f0af6-ef9d-11e5-806c-38c9ec45dc24.png)

Is that doing what you were expecting?

**Comment by D1no** [comment]
Thanks Phil, this exactly meets it. The little things.
