### ISSUE TITLE
Unhandled rejection Error: Cannot find module './Page.spec'

### ISSUE THREAD

**Issue by bcowgill** [philcockfield/ui-harness#64]
This looks really cool, but the example wont start for me :(

Solved it...

diff --git a/src/specs/index.js b/src/specs/index.js
index a150056..e7660a2 100644
--- a/src/specs/index.js
+++ b/src/specs/index.js
@@ -5,7 +5,7 @@ describe('ui-harness', function() {
   require('./skipped.spec');
   require('./it-server.spec');
   require('./PropTypes.spec');
-  require('./Page.spec');
+  require('./page.spec');
 });
 
 // External libs.

**Comment by philcockfield** [comment]
Thanks @bcowgill
