### ISSUE TITLE
Different to Storybook?

### ISSUE THREAD

**Issue by BevanR** [philcockfield/ui-harness#68]
How is UI Harness different to [React Storybook](https://github.com/kadirahq/react-storybook)?

I read #29 already.  A concise summary would be useful for anyone weighing up the two options.

**Comment by BevanR** [comment]
I asked the same question of the Storybook team: https://github.com/kadirahq/react-storybook/issues/217

**Comment by philcockfield** [comment]
Hey @BevanR - it was good to see you in the back last night.  Didn't get a chance to chat in person, but maybe at another meetup.

**Comment by philcockfield** [comment]
@BevanR if you evaluate both, I'd be interested to hear your opinions/summary.

**Comment by philcockfield** [comment]
From my understanding React StoryBook was inspired by the UIHarness project (with reference in it's [release post](https://voice.kadira.io/introducing-react-storybook-ec27f28de1e2#.fqvnzad2e) to UIHarness).

So the starting premise is going to be somewhat similar, however from there the differences are probably going to be a moving target.  @arunoda wanted to try out a bunch of different angles - and likewise we'll be moving in whatever direction dictated by the friction thrown up by our day-to-day UI development work.
