### ISSUE TITLE
Cannot assign to read only property 'key' of object '#<Object>'

### ISSUE THREAD

**Issue by hharnisc** [philcockfield/ui-harness#85]
Hey Phil, 

I'm seeing this issue updating UIHarness from **3.5.4** -> **3.12.2** (yeah I was on an old version)

```
Unhandled rejection TypeError: Cannot assign to read only property 'key' of object '#<Object>'
    at Array.forEach (native)
    at Object.mountComponent (eval at <anonymous> (http://localhost:3030/js/vendor.js:682:2), <anonymous>:46:35)
    at Object.mountComponent (eval at <anonymous> (http://localhost:3030/js/vendor.js:682:2), <anonymous>:46:35)
    at Object.mountComponent (eval at <anonymous> (http://localhost:3030/js/vendor.js:682:2), <anonymous>:46:35)
From previous event:
    at init (eval at <anonymous> (http://localhost:3030/js/vendor.js:2668:2), <anonymous>:39:39)
```

The component I'm working on looks like this:

```jsx
  before(() => {
    // this breaks
    this.component(
      <List onClick={() => console.log('List clicked')}>
        <ListItem>
          <TextListItem
            text={loremIpsum()}
          />
        </ListItem>
        <ListItem>
          <TextListItem
            text={loremIpsum()}
          />
        </ListItem>
        <ListItem>
          <TextListItem
            text={loremIpsum()}
          />
        </ListItem>
      </List>
    );
  });
```

I'm on React 15.1.0 and this works in the old version of the UIHarness. It also works when I pass **only one child** into the List component.

```jsx
  before(() => {
    // this works
    this.component(
      <List onClick={() => console.log('List clicked')}>
        <ListItem>
          <TextListItem
            text={loremIpsum()}
          />
        </ListItem>
      </List>
    );
  });
```

I think there might be something going on with the component function.

**Comment by philcockfield** [comment]
@hharnisc - try deleting your `node_modules` and reinstalling.  I've seen that before, and it seems related to Babel.

**Comment by klavs** [comment]
Same issue here.
Not even working for
``` jsx
  this.component(
    <div>
      <span>a</span>
      <span>b</span>
      <span>c</span>
    </div>
  );
```

Cleaning node_modules did not help me. Running via docker `node:6`. It must be something to do with modules, because the same code works well in sample `my-components`.

**Comment by frederickfogerty** [comment]
Same issue here - only one child works. Going to investigate further.

**Comment by philcockfield** [comment]
Fixed on release `ui-harness@3.14.2`

This will leave warnings in the console. We'll get this out as a release, then figure out how to clone the elements and give them keys to avoid any unnecessary/ugly warnings.

**Comment by klavs** [comment]
Will version in npm be updated?
In my opinion this is a critical bug.

**Comment by frederickfogerty** [comment]
Yep a new version is being pushed for this.

Get Outlook for iOS




On Thu, Jul 7, 2016 at 7:13 PM +1200, "Klāvs Priedītis" <notifications@github.com> wrote:












Will version in npm be updated?

In my opinion this is a critical bug.

**Comment by frederickfogerty** [comment]
Confirmed working on `v3.14.2` @klavs @hharnisc 🎉

**Comment by klavs** [comment]
Yep, you guys saved my yesterday's work. 😃
Btw, could this actally be caused by browser? I've seen similar error when trying to assign a value to `key`. The error was in Chrome, but not in FF. Chrome had a version with extensive es6 support, but FF, at that time, may not have had it.
